---
dependencies:
  - role: kubernetes-apps/persistent_volumes/openstack
    when:
      - cloud_provider is defined
      - cloud_provider in [ 'openstack' ]
    tags:
      - persistent_volumes_openstack

  - role: kubernetes-apps/persistent_volumes/aws
    when:
      - cloud_provider is defined
      - cloud_provider in [ 'aws' ]
    tags:
      - persistent_volumes_aws
