---
- name: Kubernetes Persistent Volumes | Lay down AWS Storage Class template
  template:
    src: "aws-storage-class.yml.j2"
    dest: "{{kube_config_dir}}/aws-storage-class.yml"
  register: manifests
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: Kubernetes Persistent Volumes | Add AWS Storage Class
  kube:
    name: storage-class
    kubectl: "{{bin_dir}}/kubectl"
    resource: StorageClass
    filename: "{{kube_config_dir}}/aws-storage-class.yml"
    state: "latest"
  when:
    - inventory_hostname == groups['kube-master'][0]
    - manifests.changed
